services:
  openldap:
    build: .
    container_name: openldap-vibhuvioio
    hostname: openldap-vibhuvioio
    env_file:
      - .env.vibhuvioio
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data-vibhuvioio:/var/lib/ldap
      - ldap-config-vibhuvioio:/etc/openldap/slapd.d
      - ./logs:/logs
      - ./custom-schema:/custom-schema:ro
    restart: unless-stopped
    networks:
      - ldap-network

volumes:
  ldap-data-vibhuvioio:
  ldap-config-vibhuvioio:

networks:
  ldap-network:
    driver: bridge
