services:
  ldap-node1:
    build: .
    container_name: ldap-node1
    hostname: ldap-node1
    env_file:
      - .env.multi-master-node1
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data-node1:/var/lib/ldap
      - ldap-config-node1:/etc/openldap/slapd.d
      - ldap-logs-node1:/logs
      - ./custom-schema:/custom-schema:ro
    restart: unless-stopped
    networks:
      - ldap-network

  ldap-node2:
    build: .
    container_name: ldap-node2
    hostname: ldap-node2
    env_file:
      - .env.multi-master-node2
    ports:
      - "390:389"
      - "637:636"
    volumes:
      - ldap-data-node2:/var/lib/ldap
      - ldap-config-node2:/etc/openldap/slapd.d
      - ldap-logs-node2:/logs
      - ./custom-schema:/custom-schema:ro
    restart: unless-stopped
    networks:
      - ldap-network
    depends_on:
      - ldap-node1

  ldap-node3:
    build: .
    container_name: ldap-node3
    hostname: ldap-node3
    env_file:
      - .env.multi-master-node3
    ports:
      - "391:389"
      - "638:636"
    volumes:
      - ldap-data-node3:/var/lib/ldap
      - ldap-config-node3:/etc/openldap/slapd.d
      - ldap-logs-node3:/logs
      - ./custom-schema:/custom-schema:ro
    restart: unless-stopped
    networks:
      - ldap-network
    depends_on:
      - ldap-node1

volumes:
  ldap-data-node1:
  ldap-config-node1:
  ldap-logs-node1:
  ldap-data-node2:
  ldap-config-node2:
  ldap-logs-node2:
  ldap-data-node3:
  ldap-config-node3:
  ldap-logs-node3:

networks:
  ldap-network:
    driver: bridge
