blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://vibhuvioio.com/ldap-manager/
    about: Check the documentation for usage guides
  - name: Discussions
    url: https://github.com/vibhuvioio/openldap-docker/discussions
    about: Ask questions and discuss features
