clusters:
  - name: "Vibhuvioio LDAP"
    host: "host.docker.internal"
    port: 389
    bind_dn: "cn=Manager,dc=vibhuvioio,dc=com"

  - name: "Local Single Node"
    host: "openldap-single"
    port: 389
    bind_dn: "cn=Manager,dc=example,dc=com"

  - name: "Local Multi-Master"
    nodes:
      - host: "ldap-node1"
        port: 389
      - host: "ldap-node2"
        port: 390
      - host: "ldap-node3"
        port: 391
    bind_dn: "cn=Manager,dc=example,dc=com"
